#!/usr/bin/python3

import sys

def factorize(number):
    for i in range(2, number):
        if number % i == 0:
            return (i, number // i)
    return None

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)
    
    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as file:
            for line in file:
                number = int(line.strip())
                factors = factorize(number)
                if factors:
                    print("{}={}*{}".format(number, factors[0], factors[1]))
                else:
                    print("{} is a prime number".format(number))
    except FileNotFoundError:
        print("File not found: {}".format(input_file))
        sys.exit(1)
    except ValueError:
        print("Invalid number in file: {}".format(input_file))
        sys.exit(1)

if __name__ == "__main__":
    main()
